### ISSUE TITLE
Compile error with missing file "algorithm".

### ISSUE THREAD

**Issue by martinyesz** [sipeed/MF1_SDK#1]
When I try to compile the MF1_SDK with the following command:
$ cmake ../../../ -DTOOLCHAIN=/opt/riscv-toolchain/bin && make

in the "MF1_SDK/src/Ai_Module_MF1_lib_test/build" folder, I got following error:
/work/working/ai_project/maix/MF1_SDK/lib/nncase/include/kernels/utils.h:16:10: fatal error: algorithm: No such file or directory
 #include <algorithm>
          ^~~~~~~~~~~
compilation terminated.
lib/CMakeFiles/kendryte.dir/build.make:62: recipe for target 'lib/CMakeFiles/kendryte.dir/drivers/sha256.c.obj' failed
make[2]: *** [lib/CMakeFiles/kendryte.dir/drivers/sha256.c.obj] Error 1
CMakeFiles/Makefile2:122: recipe for target 'lib/CMakeFiles/kendryte.dir/all' failed
make[1]: *** [lib/CMakeFiles/kendryte.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can anyone help me to find where to get this missing "algorithm" file? Thanks.

**Comment by Neutree** [comment]
maybe you can build from dev branch: https://github.com/sipeed/MF1_SDK/tree/dev

**Comment by xelll** [comment]
i will close this issue casue we use new build system.
