### ISSUE TITLE
MF1 board ,output is red screen

### ISSUE THREAD

**Issue by Tithiwat** [sipeed/MF1_SDK#14]
I found the issue [After flashing MF1.bin to the board MF1 ,output is red screen on the screen](https://github.com/sipeed/MF1_SDK/issues/5). I follow the instruction and send an email with key to support@sipeed.com but nothing feedback. Where can I download MF1 firmware?

**Comment by xelll** [comment]
Hello, what's your email address

**Comment by Tithiwat** [comment]
> Hello, what's your email address

My email is tithiwattong@gmail.com

**Comment by Tithiwat** [comment]
I got support by support@sipeed.com
