### ISSUE TITLE
MF1.bin flash on MaixGo :: unexpected result 

### ISSUE THREAD

**Issue by xhuvom** [sipeed/MF1_SDK#2]
I am trying to flash MF1 SDK on MaixGo board. So I have built and flashed the program to the maixGo
```
sudo python3 project.py build
sudo python3 project.py -B goE -p /dev/ttyUSB1 -b 1500000 -S flash
```
resulting in read screen with noises in one vertical segment . Is it yet added to run MF1 module functionalities be ported to Maix GO?

**Comment by Neutree** [comment]
Just for MF1 currently
