### ISSUE TITLE
pic.kfpkg not getting attached to MF1.bin

### ISSUE THREAD

**Issue by xhuvom** [sipeed/MF1_SDK#3]
I have created custom pic.kfpkg in MF1/main/ui/pic and then reconfigured and recompiled and then flash successfully but the previous pic.kfpkg is showing always. How to attach custom pic.kfpkg in the firmwire?

**Comment by xelll** [comment]
1. delect previous pic.kfpkg,
2. modify https://github.com/sipeed/MF1_SDK/blob/dev/projects/MF1/main/ui/pic/gen_imgbin.sh#L31
add your own pic
3. run ./gen_imgbin.sh

**Comment by xhuvom** [comment]
I have replaced "1.bmp" with my own pic and run `$ bash gen_imgbin.sh `.  The result is
```
// bmp2hex version 2.3

convert end
// bmp2hex version 2.3

convert end
// bmp2hex version 2.3

convert end
// bmp2hex version 2.3

convert end
// bmp2hex version 2.3

convert end
// bmp2hex version 2.3

convert end
// bmp2hex version 2.3

convert end
  adding: flash-list.json (deflated 76%)
  adding: 0.bin (deflated 97%)
  adding: 1.bin (deflated 90%)
  adding: 2.bin (deflated 90%)
  adding: 3.bin (deflated 91%)
  adding: 4.bin (deflated 89%)
  adding: 5.bin (deflated 98%)
  adding: 6.bin (deflated 94%)
```
Then iI run "python3 project.py rebuild" and reflash again. But still the previous image appears. What can I do?

**Comment by xelll** [comment]
you should brun pic.kfpkg to board.

**Comment by xhuvom** [comment]
I have flashed the MF1.bin and then flashed pic.kfpkg with kflash_gui too. But still the same result
