### ISSUE TITLE
"WiFi module not present" on v1.1

### ISSUE THREAD

**Issue by xhuvom** [sipeed/MF1_SDK#4]
I am trying to test the WiFi on MF1 v1.1 kit. To enable ESP8255, I have upgraded ESP8255 firmware as described [ here ](https://github.com/sipeed/MF1-User-Manual/blob/4b7e32a12ef8a6523a53c37e571deaf7651b583d/en/MF1%20module%20secondary%20development%20instructions.md#4-upgrade-esp8285-firmware) and **selected "enable network"** in **menuconfig**. 
Then when I flash the MF1 module with `-t` option, the WiFi doesn't come up. Here is the terminal log:
`
Programming BIN: |=============================================| 100.0% 52kiB/s
[INFO]Rebooting...
== flash end ==
--- forcing DTR active
--- forcing RTS active
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
manuf_id:0xc8, device_id:0x17
The header ok
there is 5 img
firmware version:
0.0.0
face_lib_version:
2019-10-14 16:16:24
e3239ab7f54be364-dirty
dump board cfg:
    out_threshold    : 88.000000
    auto_out_fea     : 0
    out_fea          : 1
    out_interval_ms  : 100
    pkt_fix          : 0
    port_baud        : 115200
    relay_open_s     : 2
    cam_flip         : 1
    cam_hmirror      : 0
    lcd_dir          : 0
    lcd_flip         : 0
    lcd_hmirror      : 0
    key              : 24
    key_dir          : 1
    log_rx           : 11
    log_tx           : 10
    port_rx          : 4
    port_tx          : 5
    relay_high       : 13
    relay_low        : 12
    user_custom_cfg  : 00000000
board key relay cfg:
	key:24	key_dir:1	relay_high:13	relay_low:12
board cfg lcd cam:
	lcd_flip:0,lcd_hmirror:0,cam_flip:1,cam_hmirror:0
lcd_set_direction: 00
camera_set_hmirror: 0
camera_set_vflip: 1
demo_esp8285
hard spi
set spi clk:8060000
Slave rx is not ready, status 0f
Slave rx is not ready, status 0f
return err
Bad CRC, request repeated
WiFiSpiDrv_getConnectionStatus-->error waitResponse
WiFi module not present
0 QR-codes found:
`
Here I can see **"WiFi module not present"** . But I wonder if its not getting the right firmware up-gradation or something else?

**Comment by xelll** [comment]
you should update esp8285 firmware
[Upgrade-ESP8285-firmware](https://github.com/sipeed/MF1-User-Manual/blob/master/en/MF1%20module%20secondary%20development%20instructions.md#4-Upgrade-ESP8285-firmware)

**Comment by xelll** [comment]
if you still have this problem,you can reopen this issue.
