### ISSUE TITLE
MF1 face lib problems

### ISSUE THREAD

**Issue by TheArheus** [sipeed/MF1_SDK#7]
Hello.

I am doing my own project for my MF1 board and I am trying to
implement string encryption. But I cannot manipulate with my string
because it causes some problems with output that string using face_lib.h.

Where can I find face_lib.c?

Thank you.

**Comment by denruss** [comment]
Hello.
I'm also wondering why some files aren't in the public domain?

**Comment by xelll** [comment]
> Hello.
> 
> I am doing my own project for my MF1 board and I am trying to
> implement string encryption. But I cannot manipulate with my string
> because it causes some problems with output that string using face_lib.h.
> 
> Where can I find face_lib.c?
> 
> Thank you.

hi,what problems you have met

**Comment by xelll** [comment]
> Hello.
> I'm also wondering why some files aren't in the public domain?

these files can not public for users

**Comment by TheArheus** [comment]
> > Hello.
> > I am doing my own project for my MF1 board and I am trying to
> > implement string encryption. But I cannot manipulate with my string
> > because it causes some problems with output that string using face_lib.h.
> > Where can I find face_lib.c?
> > Thank you.
> 
> hi,what problems you have met

Hi, I am trying to encrypt json output, but I can't find where json string is processed. I just whant to encrypt any answers from mf1 board to serial port.

**Comment by xelll** [comment]
> > > Hello.
> > > I am doing my own project for my MF1 board and I am trying to
> > > implement string encryption. But I cannot manipulate with my string
> > > because it causes some problems with output that string using face_lib.h.
> > > Where can I find face_lib.c?
> > > Thank you.
> > 
> > 
> > hi,what problems you have met
> 
> Hi, I am trying to encrypt json output, but I can't find where json string is processed. I just whant to encrypt any answers from mf1 board to serial port.

https://github.com/sipeed/MF1_SDK/blob/ab83ce9f76e3a85aa7537a3d9d6e04db6c23a7d3/projects/MF1/main/src/main.c#L61

uart_lib output json use this func.

**Comment by TheArheus** [comment]
This not really helps to me. I tried to edit string before sending to this function, but it seems it cannot output result.

**Comment by TheArheus** [comment]
I have this output as answer:
```
{"version":2,"type":"test2","code":0,"msg":"test2"}
{"version":2,"type":"test2","code":0,"msg":"test2"}
{"version":2,"type":"test","code":0,"msg":"test"}
{"version":2,"type":"pkt_prase_failed_ret","code":1,"msg":"unknown command type","cmd":"unknown"}
```
And I want to encrypt this strings with my encryption method. I tried to modify printf.h module, but it isn't helps. After that I've tried to modify uart_send function, but it also doesn't helps. Thank you

**Comment by xelll** [comment]
```C
static void uart_send(char *buf, size_t len)
{
   /* encrypt buf to new_buf */
    uart_send_data(PROTOCOL_UART_NUM, new_buf, len);
}
```

you can try like this.

**Comment by TheArheus** [comment]
Sorry for being stupid and inconsiderateble. Thank you.
