### ISSUE TITLE
please help me with single ov2640 camera

### ISSUE THREAD

**Issue by vietthao79** [sipeed/MF1_SDK#9]
i complie with single gc0328 or ov2640 and both have problem,
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(user_cmd.c.obj): in function `proto_qrcode_scan_loop':
user_cmd.c:(.text.proto_qrcode_scan_loop+0x16): undefined reference to `kpu_lock_buf'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: user_cmd.c:(.text.proto_qrcode_scan_loop+0x1e): undefined reference to `rgb_lock_buf'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: user_cmd.c:(.text.proto_qrcode_scan_loop+0x88): undefined reference to `rgb_unlock_buf'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: user_cmd.c:(.text.proto_qrcode_scan_loop+0x98): undefined reference to `kpu_unlock_buf'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj): in function `.L0 ':
face_cb.c:(.text.lcd_display_image_alpha+0x26): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj): in function `lcd_convert_cb':
face_cb.c:(.text.lcd_convert_cb+0x30): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj): in function `.L27':
face_cb.c:(.text.lcd_refresh_cb+0x26): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj): in function `.L0 ':
face_cb.c:(.text.lcd_refresh_cb+0x48): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: face_cb.c:(.text.fake_face_cb+0x20): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj):face_cb.c:(.text.pass_face_cb+0x44): more undefined references to `rgb_buf_index' follow

but complie with band sipeed lcd work well but when face recognition a while,lcd show nomemory and lcd show so lag,please help me to fix this

**Comment by xelll** [comment]
please block [user_cmd.c](https://github.com/sipeed/MF1_SDK/blob/dev/projects/MF1/main/src/user_cmd.c).it not support qrcode scan with single camera.

**Comment by vietthao79** [comment]
> please block [user_cmd.c](https://github.com/sipeed/MF1_SDK/blob/dev/projects/MF1/main/src/user_cmd.c).it not support qrcode scan with single camera.

ok.this can fix proto_qrcode.but """"rgb_buff_index""" still error,and i can not block it.because this use in board.h
<<<
#if 0
#if (!CONFIG_CAMERA_OV2640 || !CONFIG_CAMERA_GC0328_SINGLE)
extern uint8_t kpu_image_tmp[CONFIG_CAMERA_RESOLUTION_WIDTH * CONFIG_CAMERA_RESOLUTION_HEIGHT * 3];
#endif

#if CONFIG_LCD_VERTICAL
extern uint8_t display_image_ver[CONFIG_CAMERA_RESOLUTION_WIDTH * CONFIG_CAMERA_RESOLUTION_HEIGHT * 2]; //æ˜¾ç¤º
#endif

extern uint8_t kpu_image[2][CONFIG_CAMERA_RESOLUTION_WIDTH * CONFIG_CAMERA_RESOLUTION_HEIGHT * 3];
extern uint8_t display_image[CONFIG_CAMERA_RESOLUTION_WIDTH * CONFIG_CAMERA_RESOLUTION_HEIGHT * 2];
#else
extern uint8_t kpu_image[2][CONFIG_CAMERA_RESOLUTION_WIDTH * CONFIG_CAMERA_RESOLUTION_HEIGHT * 3];
extern uint8_t rgb_image[2][CONFIG_CAMERA_RESOLUTION_WIDTH * CONFIG_CAMERA_RESOLUTION_HEIGHT * 2];
----->>This---->#define display_image (rgb_image[rgb_buf_index])
#endif
>>>>


/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj): in function `.L0 ':
face_cb.c:(.text.lcd_display_image_alpha+0x26): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj): in function `lcd_convert_cb':
face_cb.c:(.text.lcd_convert_cb+0x30): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj): in function `.L27':
face_cb.c:(.text.lcd_refresh_cb+0x26): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj): in function `.L0 ':
face_cb.c:(.text.lcd_refresh_cb+0x48): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: face_cb.c:(.text.fake_face_cb+0x20): undefined reference to `rgb_buf_index'
/opt/kendryte-toolchain/lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: main/libmain.a(face_cb.c.obj):face_cb.c:(.text.pass_face_cb+0x44): more undefined references to `rgb_buf_index' follow

**Comment by xelll** [comment]
i sugest you  reset to v0.1 which commit id is c1c704d8811cde23ac2a416a3a609be51b0a5e0b

**Comment by xelll** [comment]
if you still need help,please reopen this issue.
